version: "3"

services:
  ##############################################
  ##############################################
  app-api:
    container_name: app-api
    hostname: app-api
    build:
      context: ./api/
    ports:
      - 4020:4020

    networks:
      - auth-keycloak

    entrypoint: yarn start
    restart: always
    depends_on:
      - keycloak-db

  ##############################################
  ##############################################
  app-web:
    container_name: app-web
    hostname: app-web
    build:
      context: ./web/
    ports:
      - 3000:3000

    networks:
      - auth-keycloak

    entrypoint: yarn start
    restart: always
    depends_on:
      - keycloak-db
      - app-api

  ##############################################
  ##############################################
  keycloak-db:
    image: postgres:alpine
    container_name: keycloak-db
    hostname: keycloak-db

    environment:
      - POSTGRES_PASSWORD=q1w2e3r4
      - POSTGRES_USER=keycloak_user
      - POSTGRES_DB=keycloak
    ports:
      - 5432:5432
    volumes:
      - keycloakdb:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak_user"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - auth-keycloak

  ##############################################
  ##############################################
  keycloak-host:
    container_name: keycloak-host
    hostname: keycloak-host
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin

      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-db

      DB_DATABASE: keycloak
      DB_USER: keycloak_user
      DB_SCHEMA: public
      DB_PASSWORD: q1w2e3r4

    ports:
      - 8000:8080

    depends_on:
      - keycloak-db

    networks:
      - auth-keycloak

volumes:
  keycloakdb:

networks:
  auth-keycloak:
    driver: bridge
